export type Slot = {
  time: string;
  type: "in-person" | "telehealth";
  status: "open" | "waitlist" | "booked";
};

export type Doctor = {
  id: string;
  did?: string;
  name: string;
  specialty: string;
  clinic: string;
  location: string;
  rating: number;
  reviews: number;
  fee: number;
  bookingFee: number;
  languages: string[];
  experience: string;
  telehealth: boolean;
  about: string;
  slots: Slot[];
  profileImage: string;
};

export const doctors: Doctor[] = [
  {
    id: "dr-general-physician-1",
    name: "Dr. Ananya Sen",
    specialty: "General Physician",
    clinic: "Cooch Behar City Clinic",
    location: "Cooch Behar Town",
    rating: 4.5,
    reviews: 87,
    fee: 500,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "7 years",
    telehealth: true,
    about: "Focused on family medicine, preventive care, and chronic condition management.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "open" },
      { time: "10:15 AM", type: "telehealth", status: "open" },
      { time: "1:00 PM", type: "in-person", status: "waitlist" },
      { time: "6:00 PM", type: "telehealth", status: "booked" },
    ],
    profileImage: "/doctors/dr-sen.svg",
  },
  {
    id: "dr-general-physician-2",
    name: "Dr. Ananya Basak",
    specialty: "General Physician",
    clinic: "North Bengal Skin Studio",
    location: "Dinhata",
    rating: 4.6,
    reviews: 94,
    fee: 600,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "8 years",
    telehealth: true,
    about: "Focused on family medicine, preventive care, and chronic condition management.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "open" },
      { time: "10:15 AM", type: "telehealth", status: "waitlist" },
      { time: "1:00 PM", type: "in-person", status: "booked" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-basak.svg",
  },
  {
    id: "dr-general-physician-3",
    name: "Dr. Ananya Roy",
    specialty: "General Physician",
    clinic: "Little Steps Children Care",
    location: "Tufanganj",
    rating: 4.7,
    reviews: 101,
    fee: 700,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "9 years",
    telehealth: true,
    about: "Focused on family medicine, preventive care, and chronic condition management.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "open" },
      { time: "10:15 AM", type: "telehealth", status: "waitlist" },
      { time: "1:00 PM", type: "in-person", status: "booked" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-roy.svg",
  },
  {
    id: "dr-general-physician-4",
    name: "Dr. Ananya Das",
    specialty: "General Physician",
    clinic: "Maya Women's Wellness",
    location: "Mathabhanga",
    rating: 4.8,
    reviews: 108,
    fee: 800,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "10 years",
    telehealth: true,
    about: "Focused on family medicine, preventive care, and chronic condition management.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "open" },
      { time: "10:15 AM", type: "telehealth", status: "waitlist" },
      { time: "1:00 PM", type: "in-person", status: "booked" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-das.svg",
  },
  {
    id: "dr-general-physician-5",
    name: "Dr. Ananya Ghosh",
    specialty: "General Physician",
    clinic: "Riverbank ENT Care",
    location: "Sitalkuchi",
    rating: 4.9,
    reviews: 115,
    fee: 900,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "11 years",
    telehealth: true,
    about: "Focused on family medicine, preventive care, and chronic condition management.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "open" },
      { time: "10:15 AM", type: "telehealth", status: "open" },
      { time: "1:00 PM", type: "in-person", status: "waitlist" },
      { time: "6:00 PM", type: "telehealth", status: "booked" },
    ],
    profileImage: "/doctors/dr-sen.svg",
  },
  {
    id: "dr-general-physician-6",
    name: "Dr. Ananya Banerjee",
    specialty: "General Physician",
    clinic: "Hillside Ortho Centre",
    location: "Mekhliganj",
    rating: 4.4,
    reviews: 122,
    fee: 1000,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "12 years",
    telehealth: true,
    about: "Focused on family medicine, preventive care, and chronic condition management.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "open" },
      { time: "10:15 AM", type: "telehealth", status: "open" },
      { time: "1:00 PM", type: "in-person", status: "waitlist" },
      { time: "6:00 PM", type: "telehealth", status: "booked" },
    ],
    profileImage: "/doctors/dr-basak.svg",
  },
  {
    id: "dr-general-physician-7",
    name: "Dr. Ananya Chakraborty",
    specialty: "General Physician",
    clinic: "Greenfield Family Clinic",
    location: "Cooch Behar Town",
    rating: 4.5,
    reviews: 129,
    fee: 500,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "13 years",
    telehealth: true,
    about: "Focused on family medicine, preventive care, and chronic condition management.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "waitlist" },
      { time: "10:15 AM", type: "telehealth", status: "booked" },
      { time: "1:00 PM", type: "in-person", status: "open" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-roy.svg",
  },
  {
    id: "dr-general-physician-8",
    name: "Dr. Ananya Dutta",
    specialty: "General Physician",
    clinic: "Sunrise Specialty Clinic",
    location: "Dinhata",
    rating: 4.6,
    reviews: 136,
    fee: 600,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "14 years",
    telehealth: true,
    about: "Focused on family medicine, preventive care, and chronic condition management.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "open" },
      { time: "10:15 AM", type: "telehealth", status: "waitlist" },
      { time: "1:00 PM", type: "in-person", status: "open" },
      { time: "6:00 PM", type: "telehealth", status: "booked" },
    ],
    profileImage: "/doctors/dr-das.svg",
  },
  {
    id: "dr-general-physician-9",
    name: "Dr. Ananya Saha",
    specialty: "General Physician",
    clinic: "Nursing Home Plus",
    location: "Tufanganj",
    rating: 4.7,
    reviews: 143,
    fee: 700,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "15 years",
    telehealth: true,
    about: "Focused on family medicine, preventive care, and chronic condition management.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "booked" },
      { time: "10:15 AM", type: "telehealth", status: "open" },
      { time: "1:00 PM", type: "in-person", status: "waitlist" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-sen.svg",
  },
  {
    id: "dr-general-physician-10",
    name: "Dr. Ananya Pal",
    specialty: "General Physician",
    clinic: "Township Medical Hub",
    location: "Mathabhanga",
    rating: 4.8,
    reviews: 150,
    fee: 800,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "16 years",
    telehealth: true,
    about: "Focused on family medicine, preventive care, and chronic condition management.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "booked" },
      { time: "10:15 AM", type: "telehealth", status: "waitlist" },
      { time: "1:00 PM", type: "in-person", status: "open" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-basak.svg",
  },
  {
    id: "dr-dermatologist-11",
    name: "Dr. Ananya Biswas",
    specialty: "Dermatologist",
    clinic: "Cooch Behar City Clinic",
    location: "Sitalkuchi",
    rating: 4.9,
    reviews: 157,
    fee: 900,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "17 years",
    telehealth: true,
    about: "Treating acne, allergies, and skin conditions with modern diagnostics.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "open" },
      { time: "10:15 AM", type: "telehealth", status: "waitlist" },
      { time: "1:00 PM", type: "in-person", status: "booked" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-roy.svg",
  },
  {
    id: "dr-dermatologist-12",
    name: "Dr. Ananya Mukherjee",
    specialty: "Dermatologist",
    clinic: "North Bengal Skin Studio",
    location: "Mekhliganj",
    rating: 4.4,
    reviews: 164,
    fee: 1000,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "6 years",
    telehealth: true,
    about: "Treating acne, allergies, and skin conditions with modern diagnostics.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "waitlist" },
      { time: "10:15 AM", type: "telehealth", status: "open" },
      { time: "1:00 PM", type: "in-person", status: "booked" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-das.svg",
  },
  {
    id: "dr-dermatologist-13",
    name: "Dr. Ananya Bose",
    specialty: "Dermatologist",
    clinic: "Little Steps Children Care",
    location: "Cooch Behar Town",
    rating: 4.5,
    reviews: 171,
    fee: 500,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "7 years",
    telehealth: true,
    about: "Treating acne, allergies, and skin conditions with modern diagnostics.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "waitlist" },
      { time: "10:15 AM", type: "telehealth", status: "open" },
      { time: "1:00 PM", type: "in-person", status: "open" },
      { time: "6:00 PM", type: "telehealth", status: "booked" },
    ],
    profileImage: "/doctors/dr-sen.svg",
  },
  {
    id: "dr-dermatologist-14",
    name: "Dr. Ananya Mitra",
    specialty: "Dermatologist",
    clinic: "Maya Women's Wellness",
    location: "Dinhata",
    rating: 4.6,
    reviews: 178,
    fee: 600,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "8 years",
    telehealth: true,
    about: "Treating acne, allergies, and skin conditions with modern diagnostics.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "open" },
      { time: "10:15 AM", type: "telehealth", status: "waitlist" },
      { time: "1:00 PM", type: "in-person", status: "booked" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-basak.svg",
  },
  {
    id: "dr-dermatologist-15",
    name: "Dr. Ananya Kar",
    specialty: "Dermatologist",
    clinic: "Riverbank ENT Care",
    location: "Tufanganj",
    rating: 4.7,
    reviews: 185,
    fee: 700,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "9 years",
    telehealth: true,
    about: "Treating acne, allergies, and skin conditions with modern diagnostics.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "open" },
      { time: "10:15 AM", type: "telehealth", status: "waitlist" },
      { time: "1:00 PM", type: "in-person", status: "booked" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-roy.svg",
  },
  {
    id: "dr-dermatologist-16",
    name: "Dr. Ananya Dey",
    specialty: "Dermatologist",
    clinic: "Hillside Ortho Centre",
    location: "Mathabhanga",
    rating: 4.8,
    reviews: 192,
    fee: 800,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "10 years",
    telehealth: true,
    about: "Treating acne, allergies, and skin conditions with modern diagnostics.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "waitlist" },
      { time: "10:15 AM", type: "telehealth", status: "booked" },
      { time: "1:00 PM", type: "in-person", status: "open" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-das.svg",
  },
  {
    id: "dr-dermatologist-17",
    name: "Dr. Ananya Sarkar",
    specialty: "Dermatologist",
    clinic: "Greenfield Family Clinic",
    location: "Sitalkuchi",
    rating: 4.9,
    reviews: 199,
    fee: 900,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "11 years",
    telehealth: true,
    about: "Treating acne, allergies, and skin conditions with modern diagnostics.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "waitlist" },
      { time: "10:15 AM", type: "telehealth", status: "open" },
      { time: "1:00 PM", type: "in-person", status: "booked" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-sen.svg",
  },
  {
    id: "dr-dermatologist-18",
    name: "Dr. Ananya Choudhury",
    specialty: "Dermatologist",
    clinic: "Sunrise Specialty Clinic",
    location: "Mekhliganj",
    rating: 4.4,
    reviews: 206,
    fee: 1000,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "12 years",
    telehealth: true,
    about: "Treating acne, allergies, and skin conditions with modern diagnostics.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "open" },
      { time: "10:15 AM", type: "telehealth", status: "waitlist" },
      { time: "1:00 PM", type: "in-person", status: "booked" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-basak.svg",
  },
  {
    id: "dr-dermatologist-19",
    name: "Dr. Ananya Kundu",
    specialty: "Dermatologist",
    clinic: "Nursing Home Plus",
    location: "Cooch Behar Town",
    rating: 4.5,
    reviews: 213,
    fee: 500,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "13 years",
    telehealth: true,
    about: "Treating acne, allergies, and skin conditions with modern diagnostics.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "booked" },
      { time: "10:15 AM", type: "telehealth", status: "waitlist" },
      { time: "1:00 PM", type: "in-person", status: "open" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-roy.svg",
  },
  {
    id: "dr-dermatologist-20",
    name: "Dr. Ananya Maity",
    specialty: "Dermatologist",
    clinic: "Township Medical Hub",
    location: "Dinhata",
    rating: 4.6,
    reviews: 220,
    fee: 600,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "14 years",
    telehealth: true,
    about: "Treating acne, allergies, and skin conditions with modern diagnostics.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "open" },
      { time: "10:15 AM", type: "telehealth", status: "waitlist" },
      { time: "1:00 PM", type: "in-person", status: "booked" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-das.svg",
  },
  {
    id: "dr-pediatrician-21",
    name: "Dr. Riya Sen",
    specialty: "Pediatrician",
    clinic: "Cooch Behar City Clinic",
    location: "Tufanganj",
    rating: 4.7,
    reviews: 227,
    fee: 700,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "15 years",
    telehealth: false,
    about: "Child wellness, immunizations, and growth tracking with parent-first guidance.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "booked" },
      { time: "10:15 AM", type: "telehealth", status: "open" },
      { time: "1:00 PM", type: "in-person", status: "open" },
      { time: "6:00 PM", type: "telehealth", status: "waitlist" },
    ],
    profileImage: "/doctors/dr-sen.svg",
  },
  {
    id: "dr-pediatrician-22",
    name: "Dr. Riya Basak",
    specialty: "Pediatrician",
    clinic: "North Bengal Skin Studio",
    location: "Mathabhanga",
    rating: 4.8,
    reviews: 234,
    fee: 800,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "16 years",
    telehealth: false,
    about: "Child wellness, immunizations, and growth tracking with parent-first guidance.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "booked" },
      { time: "10:15 AM", type: "telehealth", status: "open" },
      { time: "1:00 PM", type: "in-person", status: "waitlist" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-basak.svg",
  },
  {
    id: "dr-pediatrician-23",
    name: "Dr. Riya Roy",
    specialty: "Pediatrician",
    clinic: "Little Steps Children Care",
    location: "Sitalkuchi",
    rating: 4.9,
    reviews: 241,
    fee: 900,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "17 years",
    telehealth: false,
    about: "Child wellness, immunizations, and growth tracking with parent-first guidance.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "waitlist" },
      { time: "10:15 AM", type: "telehealth", status: "open" },
      { time: "1:00 PM", type: "in-person", status: "open" },
      { time: "6:00 PM", type: "telehealth", status: "booked" },
    ],
    profileImage: "/doctors/dr-roy.svg",
  },
  {
    id: "dr-pediatrician-24",
    name: "Dr. Riya Das",
    specialty: "Pediatrician",
    clinic: "Maya Women's Wellness",
    location: "Mekhliganj",
    rating: 4.4,
    reviews: 248,
    fee: 1000,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "6 years",
    telehealth: false,
    about: "Child wellness, immunizations, and growth tracking with parent-first guidance.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "waitlist" },
      { time: "10:15 AM", type: "telehealth", status: "open" },
      { time: "1:00 PM", type: "in-person", status: "booked" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-das.svg",
  },
  {
    id: "dr-pediatrician-25",
    name: "Dr. Riya Ghosh",
    specialty: "Pediatrician",
    clinic: "Riverbank ENT Care",
    location: "Cooch Behar Town",
    rating: 4.5,
    reviews: 255,
    fee: 500,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "7 years",
    telehealth: false,
    about: "Child wellness, immunizations, and growth tracking with parent-first guidance.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "open" },
      { time: "10:15 AM", type: "telehealth", status: "waitlist" },
      { time: "1:00 PM", type: "in-person", status: "booked" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-sen.svg",
  },
  {
    id: "dr-pediatrician-26",
    name: "Dr. Riya Banerjee",
    specialty: "Pediatrician",
    clinic: "Hillside Ortho Centre",
    location: "Dinhata",
    rating: 4.6,
    reviews: 262,
    fee: 600,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "8 years",
    telehealth: false,
    about: "Child wellness, immunizations, and growth tracking with parent-first guidance.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "open" },
      { time: "10:15 AM", type: "telehealth", status: "waitlist" },
      { time: "1:00 PM", type: "in-person", status: "open" },
      { time: "6:00 PM", type: "telehealth", status: "booked" },
    ],
    profileImage: "/doctors/dr-basak.svg",
  },
  {
    id: "dr-pediatrician-27",
    name: "Dr. Riya Chakraborty",
    specialty: "Pediatrician",
    clinic: "Greenfield Family Clinic",
    location: "Tufanganj",
    rating: 4.7,
    reviews: 269,
    fee: 700,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "9 years",
    telehealth: false,
    about: "Child wellness, immunizations, and growth tracking with parent-first guidance.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "booked" },
      { time: "10:15 AM", type: "telehealth", status: "open" },
      { time: "1:00 PM", type: "in-person", status: "open" },
      { time: "6:00 PM", type: "telehealth", status: "waitlist" },
    ],
    profileImage: "/doctors/dr-roy.svg",
  },
  {
    id: "dr-pediatrician-28",
    name: "Dr. Riya Dutta",
    specialty: "Pediatrician",
    clinic: "Sunrise Specialty Clinic",
    location: "Mathabhanga",
    rating: 4.8,
    reviews: 276,
    fee: 800,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "10 years",
    telehealth: false,
    about: "Child wellness, immunizations, and growth tracking with parent-first guidance.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "open" },
      { time: "10:15 AM", type: "telehealth", status: "booked" },
      { time: "1:00 PM", type: "in-person", status: "open" },
      { time: "6:00 PM", type: "telehealth", status: "waitlist" },
    ],
    profileImage: "/doctors/dr-das.svg",
  },
  {
    id: "dr-pediatrician-29",
    name: "Dr. Riya Saha",
    specialty: "Pediatrician",
    clinic: "Nursing Home Plus",
    location: "Sitalkuchi",
    rating: 4.9,
    reviews: 283,
    fee: 900,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "11 years",
    telehealth: false,
    about: "Child wellness, immunizations, and growth tracking with parent-first guidance.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "waitlist" },
      { time: "10:15 AM", type: "telehealth", status: "open" },
      { time: "1:00 PM", type: "in-person", status: "booked" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-sen.svg",
  },
  {
    id: "dr-pediatrician-30",
    name: "Dr. Riya Pal",
    specialty: "Pediatrician",
    clinic: "Township Medical Hub",
    location: "Mekhliganj",
    rating: 4.4,
    reviews: 290,
    fee: 1000,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "12 years",
    telehealth: false,
    about: "Child wellness, immunizations, and growth tracking with parent-first guidance.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "open" },
      { time: "10:15 AM", type: "telehealth", status: "booked" },
      { time: "1:00 PM", type: "in-person", status: "waitlist" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-basak.svg",
  },
  {
    id: "dr-gynecologist-31",
    name: "Dr. Riya Biswas",
    specialty: "Gynecologist",
    clinic: "Cooch Behar City Clinic",
    location: "Cooch Behar Town",
    rating: 4.5,
    reviews: 297,
    fee: 500,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "13 years",
    telehealth: true,
    about: "Women’s health, prenatal care, and confidential consultations.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "waitlist" },
      { time: "10:15 AM", type: "telehealth", status: "booked" },
      { time: "1:00 PM", type: "in-person", status: "open" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-roy.svg",
  },
  {
    id: "dr-gynecologist-32",
    name: "Dr. Riya Mukherjee",
    specialty: "Gynecologist",
    clinic: "North Bengal Skin Studio",
    location: "Dinhata",
    rating: 4.6,
    reviews: 304,
    fee: 600,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "14 years",
    telehealth: true,
    about: "Women’s health, prenatal care, and confidential consultations.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "open" },
      { time: "10:15 AM", type: "telehealth", status: "waitlist" },
      { time: "1:00 PM", type: "in-person", status: "booked" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-das.svg",
  },
  {
    id: "dr-gynecologist-33",
    name: "Dr. Riya Bose",
    specialty: "Gynecologist",
    clinic: "Little Steps Children Care",
    location: "Tufanganj",
    rating: 4.7,
    reviews: 311,
    fee: 700,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "15 years",
    telehealth: true,
    about: "Women’s health, prenatal care, and confidential consultations.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "waitlist" },
      { time: "10:15 AM", type: "telehealth", status: "open" },
      { time: "1:00 PM", type: "in-person", status: "open" },
      { time: "6:00 PM", type: "telehealth", status: "booked" },
    ],
    profileImage: "/doctors/dr-sen.svg",
  },
  {
    id: "dr-gynecologist-34",
    name: "Dr. Riya Mitra",
    specialty: "Gynecologist",
    clinic: "Maya Women's Wellness",
    location: "Mathabhanga",
    rating: 4.8,
    reviews: 318,
    fee: 800,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "16 years",
    telehealth: true,
    about: "Women’s health, prenatal care, and confidential consultations.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "open" },
      { time: "10:15 AM", type: "telehealth", status: "waitlist" },
      { time: "1:00 PM", type: "in-person", status: "booked" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-basak.svg",
  },
  {
    id: "dr-gynecologist-35",
    name: "Dr. Riya Kar",
    specialty: "Gynecologist",
    clinic: "Riverbank ENT Care",
    location: "Sitalkuchi",
    rating: 4.9,
    reviews: 325,
    fee: 900,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "17 years",
    telehealth: true,
    about: "Women’s health, prenatal care, and confidential consultations.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "waitlist" },
      { time: "10:15 AM", type: "telehealth", status: "open" },
      { time: "1:00 PM", type: "in-person", status: "booked" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-roy.svg",
  },
  {
    id: "dr-gynecologist-36",
    name: "Dr. Riya Dey",
    specialty: "Gynecologist",
    clinic: "Hillside Ortho Centre",
    location: "Mekhliganj",
    rating: 4.4,
    reviews: 332,
    fee: 1000,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "6 years",
    telehealth: true,
    about: "Women’s health, prenatal care, and confidential consultations.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "booked" },
      { time: "10:15 AM", type: "telehealth", status: "waitlist" },
      { time: "1:00 PM", type: "in-person", status: "open" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-das.svg",
  },
  {
    id: "dr-gynecologist-37",
    name: "Dr. Riya Sarkar",
    specialty: "Gynecologist",
    clinic: "Greenfield Family Clinic",
    location: "Cooch Behar Town",
    rating: 4.5,
    reviews: 339,
    fee: 500,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "7 years",
    telehealth: true,
    about: "Women’s health, prenatal care, and confidential consultations.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "waitlist" },
      { time: "10:15 AM", type: "telehealth", status: "booked" },
      { time: "1:00 PM", type: "in-person", status: "open" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-sen.svg",
  },
  {
    id: "dr-gynecologist-38",
    name: "Dr. Riya Choudhury",
    specialty: "Gynecologist",
    clinic: "Sunrise Specialty Clinic",
    location: "Dinhata",
    rating: 4.6,
    reviews: 346,
    fee: 600,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "8 years",
    telehealth: true,
    about: "Women’s health, prenatal care, and confidential consultations.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "open" },
      { time: "10:15 AM", type: "telehealth", status: "open" },
      { time: "1:00 PM", type: "in-person", status: "waitlist" },
      { time: "6:00 PM", type: "telehealth", status: "booked" },
    ],
    profileImage: "/doctors/dr-basak.svg",
  },
  {
    id: "dr-gynecologist-39",
    name: "Dr. Riya Kundu",
    specialty: "Gynecologist",
    clinic: "Nursing Home Plus",
    location: "Tufanganj",
    rating: 4.7,
    reviews: 353,
    fee: 700,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "9 years",
    telehealth: true,
    about: "Women’s health, prenatal care, and confidential consultations.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "open" },
      { time: "10:15 AM", type: "telehealth", status: "booked" },
      { time: "1:00 PM", type: "in-person", status: "waitlist" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-roy.svg",
  },
  {
    id: "dr-gynecologist-40",
    name: "Dr. Riya Maity",
    specialty: "Gynecologist",
    clinic: "Township Medical Hub",
    location: "Mathabhanga",
    rating: 4.8,
    reviews: 360,
    fee: 800,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "10 years",
    telehealth: true,
    about: "Women’s health, prenatal care, and confidential consultations.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "waitlist" },
      { time: "10:15 AM", type: "telehealth", status: "open" },
      { time: "1:00 PM", type: "in-person", status: "booked" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-das.svg",
  },
  {
    id: "dr-ent-41",
    name: "Dr. Arup Sen",
    specialty: "ENT",
    clinic: "Cooch Behar City Clinic",
    location: "Sitalkuchi",
    rating: 4.9,
    reviews: 367,
    fee: 900,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "11 years",
    telehealth: true,
    about: "Ear, nose, and throat care with quick relief for infections and allergies.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "open" },
      { time: "10:15 AM", type: "telehealth", status: "waitlist" },
      { time: "1:00 PM", type: "in-person", status: "booked" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-sen.svg",
  },
  {
    id: "dr-ent-42",
    name: "Dr. Arup Basak",
    specialty: "ENT",
    clinic: "North Bengal Skin Studio",
    location: "Mekhliganj",
    rating: 4.4,
    reviews: 374,
    fee: 1000,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "12 years",
    telehealth: true,
    about: "Ear, nose, and throat care with quick relief for infections and allergies.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "booked" },
      { time: "10:15 AM", type: "telehealth", status: "open" },
      { time: "1:00 PM", type: "in-person", status: "open" },
      { time: "6:00 PM", type: "telehealth", status: "waitlist" },
    ],
    profileImage: "/doctors/dr-basak.svg",
  },
  {
    id: "dr-ent-43",
    name: "Dr. Arup Roy",
    specialty: "ENT",
    clinic: "Little Steps Children Care",
    location: "Cooch Behar Town",
    rating: 4.5,
    reviews: 381,
    fee: 500,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "13 years",
    telehealth: true,
    about: "Ear, nose, and throat care with quick relief for infections and allergies.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "open" },
      { time: "10:15 AM", type: "telehealth", status: "open" },
      { time: "1:00 PM", type: "in-person", status: "booked" },
      { time: "6:00 PM", type: "telehealth", status: "waitlist" },
    ],
    profileImage: "/doctors/dr-roy.svg",
  },
  {
    id: "dr-ent-44",
    name: "Dr. Arup Das",
    specialty: "ENT",
    clinic: "Maya Women's Wellness",
    location: "Dinhata",
    rating: 4.6,
    reviews: 388,
    fee: 600,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "14 years",
    telehealth: true,
    about: "Ear, nose, and throat care with quick relief for infections and allergies.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "open" },
      { time: "10:15 AM", type: "telehealth", status: "open" },
      { time: "1:00 PM", type: "in-person", status: "booked" },
      { time: "6:00 PM", type: "telehealth", status: "waitlist" },
    ],
    profileImage: "/doctors/dr-das.svg",
  },
  {
    id: "dr-ent-45",
    name: "Dr. Arup Ghosh",
    specialty: "ENT",
    clinic: "Riverbank ENT Care",
    location: "Tufanganj",
    rating: 4.7,
    reviews: 395,
    fee: 700,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "15 years",
    telehealth: true,
    about: "Ear, nose, and throat care with quick relief for infections and allergies.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "waitlist" },
      { time: "10:15 AM", type: "telehealth", status: "open" },
      { time: "1:00 PM", type: "in-person", status: "booked" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-sen.svg",
  },
  {
    id: "dr-ent-46",
    name: "Dr. Arup Banerjee",
    specialty: "ENT",
    clinic: "Hillside Ortho Centre",
    location: "Mathabhanga",
    rating: 4.8,
    reviews: 402,
    fee: 800,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "16 years",
    telehealth: true,
    about: "Ear, nose, and throat care with quick relief for infections and allergies.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "open" },
      { time: "10:15 AM", type: "telehealth", status: "booked" },
      { time: "1:00 PM", type: "in-person", status: "waitlist" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-basak.svg",
  },
  {
    id: "dr-ent-47",
    name: "Dr. Arup Chakraborty",
    specialty: "ENT",
    clinic: "Greenfield Family Clinic",
    location: "Sitalkuchi",
    rating: 4.9,
    reviews: 409,
    fee: 900,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "17 years",
    telehealth: true,
    about: "Ear, nose, and throat care with quick relief for infections and allergies.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "waitlist" },
      { time: "10:15 AM", type: "telehealth", status: "open" },
      { time: "1:00 PM", type: "in-person", status: "booked" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-roy.svg",
  },
  {
    id: "dr-ent-48",
    name: "Dr. Arup Dutta",
    specialty: "ENT",
    clinic: "Sunrise Specialty Clinic",
    location: "Mekhliganj",
    rating: 4.4,
    reviews: 416,
    fee: 1000,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "6 years",
    telehealth: true,
    about: "Ear, nose, and throat care with quick relief for infections and allergies.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "open" },
      { time: "10:15 AM", type: "telehealth", status: "open" },
      { time: "1:00 PM", type: "in-person", status: "waitlist" },
      { time: "6:00 PM", type: "telehealth", status: "booked" },
    ],
    profileImage: "/doctors/dr-das.svg",
  },
  {
    id: "dr-ent-49",
    name: "Dr. Arup Saha",
    specialty: "ENT",
    clinic: "Nursing Home Plus",
    location: "Cooch Behar Town",
    rating: 4.5,
    reviews: 423,
    fee: 500,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "7 years",
    telehealth: true,
    about: "Ear, nose, and throat care with quick relief for infections and allergies.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "booked" },
      { time: "10:15 AM", type: "telehealth", status: "open" },
      { time: "1:00 PM", type: "in-person", status: "open" },
      { time: "6:00 PM", type: "telehealth", status: "waitlist" },
    ],
    profileImage: "/doctors/dr-sen.svg",
  },
  {
    id: "dr-ent-50",
    name: "Dr. Arup Pal",
    specialty: "ENT",
    clinic: "Township Medical Hub",
    location: "Dinhata",
    rating: 4.6,
    reviews: 430,
    fee: 600,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "8 years",
    telehealth: true,
    about: "Ear, nose, and throat care with quick relief for infections and allergies.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "waitlist" },
      { time: "10:15 AM", type: "telehealth", status: "open" },
      { time: "1:00 PM", type: "in-person", status: "open" },
      { time: "6:00 PM", type: "telehealth", status: "booked" },
    ],
    profileImage: "/doctors/dr-basak.svg",
  },
  {
    id: "dr-orthopedic-51",
    name: "Dr. Arup Biswas",
    specialty: "Orthopedic",
    clinic: "Cooch Behar City Clinic",
    location: "Tufanganj",
    rating: 4.7,
    reviews: 437,
    fee: 700,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "9 years",
    telehealth: false,
    about: "Bone, joint, and sports injury care with rehab planning.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "open" },
      { time: "10:15 AM", type: "telehealth", status: "booked" },
      { time: "1:00 PM", type: "in-person", status: "waitlist" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-roy.svg",
  },
  {
    id: "dr-orthopedic-52",
    name: "Dr. Arup Mukherjee",
    specialty: "Orthopedic",
    clinic: "North Bengal Skin Studio",
    location: "Mathabhanga",
    rating: 4.8,
    reviews: 444,
    fee: 800,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "10 years",
    telehealth: false,
    about: "Bone, joint, and sports injury care with rehab planning.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "waitlist" },
      { time: "10:15 AM", type: "telehealth", status: "open" },
      { time: "1:00 PM", type: "in-person", status: "booked" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-das.svg",
  },
  {
    id: "dr-orthopedic-53",
    name: "Dr. Arup Bose",
    specialty: "Orthopedic",
    clinic: "Little Steps Children Care",
    location: "Sitalkuchi",
    rating: 4.9,
    reviews: 451,
    fee: 900,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "11 years",
    telehealth: false,
    about: "Bone, joint, and sports injury care with rehab planning.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "open" },
      { time: "10:15 AM", type: "telehealth", status: "open" },
      { time: "1:00 PM", type: "in-person", status: "waitlist" },
      { time: "6:00 PM", type: "telehealth", status: "booked" },
    ],
    profileImage: "/doctors/dr-sen.svg",
  },
  {
    id: "dr-orthopedic-54",
    name: "Dr. Arup Mitra",
    specialty: "Orthopedic",
    clinic: "Maya Women's Wellness",
    location: "Mekhliganj",
    rating: 4.4,
    reviews: 458,
    fee: 1000,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "12 years",
    telehealth: false,
    about: "Bone, joint, and sports injury care with rehab planning.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "waitlist" },
      { time: "10:15 AM", type: "telehealth", status: "booked" },
      { time: "1:00 PM", type: "in-person", status: "open" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-basak.svg",
  },
  {
    id: "dr-orthopedic-55",
    name: "Dr. Arup Kar",
    specialty: "Orthopedic",
    clinic: "Riverbank ENT Care",
    location: "Cooch Behar Town",
    rating: 4.5,
    reviews: 465,
    fee: 500,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "13 years",
    telehealth: false,
    about: "Bone, joint, and sports injury care with rehab planning.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "open" },
      { time: "10:15 AM", type: "telehealth", status: "waitlist" },
      { time: "1:00 PM", type: "in-person", status: "booked" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-roy.svg",
  },
  {
    id: "dr-orthopedic-56",
    name: "Dr. Arup Dey",
    specialty: "Orthopedic",
    clinic: "Hillside Ortho Centre",
    location: "Dinhata",
    rating: 4.6,
    reviews: 472,
    fee: 600,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "14 years",
    telehealth: false,
    about: "Bone, joint, and sports injury care with rehab planning.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "waitlist" },
      { time: "10:15 AM", type: "telehealth", status: "open" },
      { time: "1:00 PM", type: "in-person", status: "open" },
      { time: "6:00 PM", type: "telehealth", status: "booked" },
    ],
    profileImage: "/doctors/dr-das.svg",
  },
  {
    id: "dr-orthopedic-57",
    name: "Dr. Arup Sarkar",
    specialty: "Orthopedic",
    clinic: "Greenfield Family Clinic",
    location: "Tufanganj",
    rating: 4.7,
    reviews: 479,
    fee: 700,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "15 years",
    telehealth: false,
    about: "Bone, joint, and sports injury care with rehab planning.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "waitlist" },
      { time: "10:15 AM", type: "telehealth", status: "booked" },
      { time: "1:00 PM", type: "in-person", status: "open" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-sen.svg",
  },
  {
    id: "dr-orthopedic-58",
    name: "Dr. Arup Choudhury",
    specialty: "Orthopedic",
    clinic: "Sunrise Specialty Clinic",
    location: "Mathabhanga",
    rating: 4.8,
    reviews: 86,
    fee: 800,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "16 years",
    telehealth: false,
    about: "Bone, joint, and sports injury care with rehab planning.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "open" },
      { time: "10:15 AM", type: "telehealth", status: "open" },
      { time: "1:00 PM", type: "in-person", status: "booked" },
      { time: "6:00 PM", type: "telehealth", status: "waitlist" },
    ],
    profileImage: "/doctors/dr-basak.svg",
  },
  {
    id: "dr-orthopedic-59",
    name: "Dr. Arup Kundu",
    specialty: "Orthopedic",
    clinic: "Nursing Home Plus",
    location: "Sitalkuchi",
    rating: 4.9,
    reviews: 93,
    fee: 900,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "17 years",
    telehealth: false,
    about: "Bone, joint, and sports injury care with rehab planning.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "open" },
      { time: "10:15 AM", type: "telehealth", status: "open" },
      { time: "1:00 PM", type: "in-person", status: "waitlist" },
      { time: "6:00 PM", type: "telehealth", status: "booked" },
    ],
    profileImage: "/doctors/dr-roy.svg",
  },
  {
    id: "dr-orthopedic-60",
    name: "Dr. Arup Maity",
    specialty: "Orthopedic",
    clinic: "Township Medical Hub",
    location: "Mekhliganj",
    rating: 4.4,
    reviews: 100,
    fee: 1000,
    bookingFee: 10,
    languages: ["Bengali", "English"],
    experience: "6 years",
    telehealth: false,
    about: "Bone, joint, and sports injury care with rehab planning.",
    slots: [
      { time: "9:30 AM", type: "in-person", status: "open" },
      { time: "10:15 AM", type: "telehealth", status: "booked" },
      { time: "1:00 PM", type: "in-person", status: "waitlist" },
      { time: "6:00 PM", type: "telehealth", status: "open" },
    ],
    profileImage: "/doctors/dr-das.svg",
  },
];

export type Booking = {
  id: string;
  doctor: string;
  clinic: string;
  date: string;
  time: string;
  type: "in-person" | "telehealth";
  status: "upcoming" | "completed";
};

export const bookings: Booking[] = [
  {
    id: "bk-101",
    doctor: "Dr. Ananya Sen",
    clinic: "Cooch Behar City Clinic",
    date: "Tomorrow",
    time: "4:30 PM",
    type: "telehealth",
    status: "upcoming",
  },
  {
    id: "bk-102",
    doctor: "Dr. Riya Basak",
    clinic: "North Bengal Skin Studio",
    date: "Feb 6",
    time: "1:15 PM",
    type: "in-person",
    status: "upcoming",
  },
  {
    id: "bk-103",
    doctor: "Dr. Arup Roy",
    clinic: "Little Steps Children Care",
    date: "Jan 28",
    time: "9:30 AM",
    type: "in-person",
    status: "completed",
  },
];

export type ClinicDay = {
  day: string;
  slots: { time: string; status: "open" | "booked" | "blocked" }[];
};

export type ClinicCalendar = {
  doctorId: string;
  doctorName: string;
  clinic: string;
  location: string;
  schedule: ClinicDay[];
};

export const clinicCalendars: ClinicCalendar[] = [
  {
    doctorId: "dr-sen",
    doctorName: "Dr. Ananya Sen",
    clinic: "Cooch Behar City Clinic",
    location: "Cooch Behar Town",
    schedule: [
      { day: "Mon", slots: [
        { time: "10:00 AM", status: "open" },
        { time: "10:30 AM", status: "booked" },
        { time: "11:00 AM", status: "open" },
        { time: "4:00 PM", status: "open" },
      ] },
      { day: "Tue", slots: [
        { time: "9:30 AM", status: "open" },
        { time: "10:00 AM", status: "booked" },
        { time: "4:30 PM", status: "open" },
      ] },
    ],
  },
  {
    doctorId: "dr-basak",
    doctorName: "Dr. Riya Basak",
    clinic: "North Bengal Skin Studio",
    location: "Tufanganj",
    schedule: [
      { day: "Wed", slots: [
        { time: "11:00 AM", status: "open" },
        { time: "11:30 AM", status: "booked" },
        { time: "5:00 PM", status: "open" },
      ] },
      { day: "Thu", slots: [
        { time: "10:15 AM", status: "open" },
        { time: "1:30 PM", status: "booked" },
        { time: "6:00 PM", status: "open" },
      ] },
    ],
  },
  {
    doctorId: "dr-roy",
    doctorName: "Dr. Arup Roy",
    clinic: "Little Steps Children Care",
    location: "Dinhata",
    schedule: [
      { day: "Mon", slots: [
        { time: "8:30 AM", status: "open" },
        { time: "9:00 AM", status: "open" },
        { time: "2:30 PM", status: "booked" },
      ] },
      { day: "Sat", slots: [
        { time: "9:30 AM", status: "open" },
        { time: "10:00 AM", status: "open" },
        { time: "11:00 AM", status: "booked" },
      ] },
    ],
  },
  {
    doctorId: "dr-das",
    doctorName: "Dr. Swati Das",
    clinic: "Maya Women's Wellness",
    location: "Mathabhanga",
    schedule: [
      { day: "Tue", slots: [
        { time: "10:00 AM", status: "open" },
        { time: "12:30 PM", status: "open" },
        { time: "3:30 PM", status: "booked" },
      ] },
      { day: "Fri", slots: [
        { time: "11:00 AM", status: "open" },
        { time: "6:30 PM", status: "open" },
        { time: "7:00 PM", status: "booked" },
      ] },
    ],
  },
];

export type CalendarDay = {
  label: string;
  weekday: string;
  status: "available" | "fast-filling" | "booked";
};

export type AvailabilityStatus = "available" | "late" | "not available";

const monthNames = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
const weekNames = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

function seedFromString(value: string) {
  let hash = 0;
  for (let i = 0; i < value.length; i += 1) {
    hash = (hash * 31 + value.charCodeAt(i)) >>> 0;
  }
  return hash || 1;
}

function mulberry32(seed: number) {
  return function () {
    let t = (seed += 0x6d2b79f5);
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export function getDemoCalendar(doctorId: string, days = 28): CalendarDay[] {
  const rand = mulberry32(seedFromString(doctorId));
  const today = new Date();
  const results: CalendarDay[] = [];

  for (let i = 0; i < days; i += 1) {
    const date = new Date(today);
    date.setDate(today.getDate() + i);
    const r = rand();
    const status = r < 0.22 ? "booked" : r < 0.45 ? "fast-filling" : "available";
    results.push({
      label: `${date.getDate()} ${monthNames[date.getMonth()]}`,
      weekday: weekNames[date.getDay()],
      status,
    });
  }

  return results;
}

// Simple helpers for directory/availability summaries (demo-only).
export function getClinicCalendarByDoctorId(doctorId: string) {
  return clinicCalendars.find((calendar) => calendar.doctorId === doctorId);
}

export function getVisitingSummary(doctorId: string) {
  const calendar = getClinicCalendarByDoctorId(doctorId);
  if (!calendar) return { days: "Varies", timeRange: "Check availability" };

  const days = calendar.schedule.map((day) => day.day).join(", ");
  const allTimes = calendar.schedule.flatMap((day) => day.slots.map((slot) => slot.time));
  if (allTimes.length === 0) return { days, timeRange: "Check availability" };

  const timeRange = `${allTimes[0]} - ${allTimes[allTimes.length - 1]}`;
  return { days, timeRange };
}

export function getTodayAvailabilityStatus(doctorId: string): AvailabilityStatus {
  const today = getDemoCalendar(doctorId, 1)[0];
  if (!today) return "not available";
  if (today.status === "available") return "available";
  if (today.status === "fast-filling") return "late";
  return "not available";
}

export const neighborhoods = [
  "Cooch Behar Town",
  "Dinhata",
  "Tufanganj",
  "Mathabhanga",
  "Sitalkuchi",
  "Mekhliganj",
];

export const specialties = [
  "General Physician",
  "Dermatologist",
  "Pediatrician",
  "Gynecologist",
  "ENT",
  "Orthopedic",
];
